--NOTE: Disabled this config in favor of easy-dotnet.nvim. I will revert to this if issues come about.


-- --Plugin for configuring roslyn language server for C#
--
-- -- local roslyn_path = vim.fn.stdpath("data") ..
-- --     "/mason/packages/roslyn/libexec/" .. "Microsoft.CodeAnalysis.LanguageServer.dll"
--
-- local function insert_summary_comment(isBelow)
--     local target_comment_row = vim.api.nvim_win_get_cursor(0)[1] - 1
--
--     if (isBelow) then
--         target_comment_row = target_comment_row + 1
--     end
--
--     local lines = { "/// <summary>", "/// ", "/// </summary>" }
--     vim.api.nvim_buf_set_lines(0, target_comment_row, target_comment_row, false, lines)
--     vim.lsp.buf.format()
--
--     local row = vim.api.nvim_win_get_cursor(0)[1]
--     local target_row
--     if (isBelow) then
--         target_row = row + 2
--     else
--         target_row = row - 2
--     end
--     vim.api.nvim_win_set_cursor(0, { target_row, vim.v.maxcol })
--     vim.api.nvim_input("a")
-- end
--
-- return {
--     {
--         "seblj/roslyn.nvim",
--         --Lazy loading seems to prevent lsp from watching new files correctly
--         -- ft = { "cs", "razor" },
--         -- cmd = { "Roslyn" },
--         enabled = false,
--         init = function()
--             vim.filetype.add {
--                 extension = {
--                     razor = 'razor',
--                     cshtml = 'razor',
--                 },
--             }
--         end,
--         opts = {
--             silent = false,
--             filewatching = "roslyn"
--         },
--         config = function(_, opts)
--             vim.lsp.config("roslyn", {
--                 settings = {
--                     ['csharp|inlay_hints'] = {
--                         csharp_enable_inlay_hints_for_implicit_object_creation = true,
--                         csharp_enable_inlay_hints_for_implicit_variable_types = true,
--
--                         csharp_enable_inlay_hints_for_lambda_parameter_types = true,
--                         csharp_enable_inlay_hints_for_types = true,
--                         dotnet_enable_inlay_hints_for_indexer_parameters = true,
--                         dotnet_enable_inlay_hints_for_literal_parameters = true,
--                         dotnet_enable_inlay_hints_for_object_creation_parameters = true,
--                         dotnet_enable_inlay_hints_for_other_parameters = true,
--                         dotnet_enable_inlay_hints_for_parameters = true,
--                         dotnet_suppress_inlay_hints_for_parameters_that_differ_only_by_suffix = true,
--                         dotnet_suppress_inlay_hints_for_parameters_that_match_argument_name = true,
--                         dotnet_suppress_inlay_hints_for_parameters_that_match_method_intent = true,
--                     },
--                     ['csharp|code_lens'] = {
--                         dotnet_enable_references_code_lens = true,
--                     },
--                 },
--             })
--
--
--             vim.api.nvim_create_autocmd({ "FileType" }, {
--                 callback = function()
--                     if vim.opt.filetype:get() == 'cs' then
--                         vim.keymap.set("n", "<leader>tsk", function()
--                             insert_summary_comment(false)
--                         end, { desc = "Create summary comment above cursor" })
--
--
--                         vim.keymap.set("n", "<leader>tsj", function()
--                             insert_summary_comment(true)
--                         end, { desc = "Create summary comment below cursor" })
--                     end
--                 end
--             })
--
--             require('roslyn').setup(opts)
--         end
--     }
-- }
