require("core.lspconfig.luaserver")
require("core.lspconfig.typescriptserver")
--require("core.lspconfig.omnisharp-mono")
require("core.lspconfig.csharpserver")
require("core.lspconfig.arduinoserver")
--require("core.lspconfig.vue2server")
require("core.lspconfig.vue3server")
require("core.lspconfig.rustserver")
